sudo: required
services:
    - docker
    
before_install:
    - docker build -t erictung1999/test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true erictung1999/test npm test -- --coverage
    
after_success:
    - docker build -t erictung1999/client ./client
    - docker build -t erictung1999/nginx ./nginx
    - docker build -t erictung1999/server ./server
    - docker build -t erictung1999/worker ./worker
    - echo $DOCKER_PASSWORD | docker login --username $DOCKER_ID --password-stdin
    - docker push erictung1999/client
    - docker push erictung1999/nginx
    - docker push erictung1999/server
    - docker push erictung1999/worker
    
deploy:
    edge: true
    provider: elasticbeanstalk
    region: ap-southeast-1
    app: multi-docker-fibcalc
    env: MultiDockerFibcalc-env
    bucket_name: elasticbeanstalk-ap-southeast-1-718737905471
    bucket_path: docker-multi
    on:
        branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
    